### ISSUE TITLE
Error attempting to play a video (any video)

### ISSUE THREAD

**Issue by drewjc75** [matejdro/plugin.video.nebula#3] opened 2020-07-22 01:54 UTC
```
2020-07-21 21:49:24.292 T:5192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
     Error Type: <type 'exceptions.TypeError'>
     Error Contents: 'NoneType' object has no attribute '__getitem__'
     Traceback (most recent call last):
     File "C:\Users\Andrew\AppData\Roaming\Kodi\addons\plugin.video.nebula\main.py", line 127, in <module>
          router(dict(parse_qsl(sys.argv[2][1:])))
     File "C:\Users\Andrew\AppData\Roaming\Kodi\addons\plugin.video.nebula\main.py", line 118, in router
          play_video(params["id"])
     File "C:\Users\Andrew\AppData\Roaming\Kodi\addons\plugin.video.nebula\main.py", line 81, in play_video
          url = videos.get_video_url(id)
     File "C:\Users\Andrew\AppData\Roaming\Kodi\addons\plugin.video.nebula\nebulalib\videos.py", line 6, in get_video_url
          manifest = api.get_video_manifest(video_id)
     File "C:\Users\Andrew\AppData\Roaming\Kodi\addons\plugin.video.nebula\nebulalib\api.py", line 91, in get_video_manifest
          login()
     File "C:\Users\Andrew\AppData\Roaming\Kodi\addons\plugin.video.nebula\nebulalib\api.py", line 50, in login
          user_data_body.json()["zype_auth_info"]["access_token"]
     TypeError: 'NoneType' object has no attribute '__getitem__'
-->End of Python script error report<--
2020-07-21 21:49:24.358 T:3976   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nebula/?action=video&id=5f0cf6733ba6da0001d521c5]
```

**Comment by matejdro** [comment] 2020-07-23 15:09
Duplicate of https://github.com/matejdro/plugin.video.nebula/issues/2.

Please try to log out and login from the nebula in the browser and see if it helps.

**Closed as completed by matejdro** 2020-07-23 15:09 UTC
